kotlin.code.style=official
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod Data
mod_version=4.0.0
maven_group=space.rogi27
archives_base_name=homabric

# Minecraft
minecraft_version_group=26.3.x
minecraft_version=26.3
loader_version=0.19.5

# Fabric
fabric_api_version=0.160.5+26.3
loom_version=1.17-SNAPSHOT

# Kotlin
kotlin_version=2.4.20
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# Libs
fabric_permissions_api_version=0.7.0
sgui_version=2.2.0+26.3
server_translations_api_version=3.2.0+26.3
configurate_version=4.2.0